// gestionador-frontend/src/page/Register.jsx
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {registerRequest} from '../api/auth.js';
import Respuesta from '../components/Repuesta.jsx';

export default function Register() {

    const navigate = useNavigate();
    const [valido, setValido] = useState(null);

    const handleSubmit = async (e) => {
        e.preventDefault();// Evitar el comportamiento por defecto del formulario
        try {
            await registerRequest(form); // formData es tu objeto con los datos del formulario
            setValido(true); // Registro exitoso
            setTimeout(() => {
                navigate('/');
            },2000);
        } catch (error) {
        setValido(false); // Registro fallido
        }
    }


    const [form, setForm]=useState({
        name:'',
        password:'',
        role: '',
        ci:'',
        telefono:''
    })

    const handleChange = (e) => {
        const { name, value } = e.target;
        setForm(form =>({
            ...form,
            [name]: value
        }));  
        setValido(null); // Reiniciar el estado de valido al cambiar el formulario
    }

    return (
        <main className="grid grid-cols-3 grid-rows-3 h-screen w-screen">
            <button className='col-start-1 row-start-1 bg-blue-700 font-sans justify-self-start self-start ml-5 mt-5
            h-auto max-w-min w-full p-3 border-2 rounded-2xl font-bold text-2xl' onClick={
                () => navigate('/')
            }>⬅Volver</button>
            <form className="grid grid-cols-1 col-start-2 row-start-2 gap-2 max-w-md w-full px-5 py-10 h-auto bg-blue-600 justify-self-center self-center items-center  border-2 rounded-xl" onSubmit={handleSubmit}>
                <h1 className='relative font-bold text-4xl left-1'>Registro</h1>
                <label htmlFor="usuarioname" className='font-sans text-lg'>☛nombre de usuario</label>
                <input type="text" id="username" name='name' className='rounded-sm bg-blue-400
                border-2' required onChange={handleChange}/>
                
                <label htmlFor="password" className='font-sans text-lg'>☛Contraseña</label>
                <input type="password" id="password" name='password'className='rounded-sm bg-blue-400
                border-2' required onChange={handleChange}/>
        
                <label htmlFor="ci" className='font-sans text-lg'>☛Carnet de identidad</label>
                <input type="text" id="ci" name='ci'className='rounded-sm bg-blue-400
                border-2' required onChange={handleChange}/>

                <label htmlFor="telefono" className='font-sans text-lg'>☛Numero de telefono</label>
                <input type="test" id="telefono" name='telefono' className='rounded-sm bg-blue-400
                border-2' required onChange={handleChange}/>

                <label for="role-select" className='font-sans text-lg'>☛Tipo de usuario:</label>
                    <select name="role" id="role-select" className="bg-blue-200 border-2" onChange={handleChange}>
                    <option value="">--Seleccione un rol--</option>
                    <option value="vendedor">Vendedor</option>
                    <option value="proveedor">Proveedor</option>
                    </select>
                <button type="submit" className='font-sans font-bold border-2 relative  bg-blue-200 w-30 rounded-sm h-10'>
                    Crear cuenta
                </button>
            </form>
            {valido !== null && <Respuesta valido={valido} className="relative top-2"/>}
        </main>
    )
}

// gestionador-frontend-angular/src/app/pages/register/register.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';


@Component({
  selector: 'app-register',
  standalone: true,
  imports: [ReactiveFormsModule],
  template: `
<main class="grid grid-cols-3 grid-rows-3 h-screen w-screen">
  <button class="col-start-1 row-start-1 justify-self-start self-start ml-5 mt-5
    h-auto max-w-min w-full p-3 border-2 rounded-2xl font-bold text-2xl"
    (click)="home()">⬅Volver</button>
  <form [formGroup]="registerForm"
        class="grid grid-cols-1 col-start-2 row-start-2 gap-4 max-w-md w-full px-5 py-10 h-auto justify-self-center self-center items-center border-2 rounded-xl"
        (ngSubmit)="onSubmit()">
    <h1 class="relative font-bold text-4xl left-1">Registro</h1>
    <label class="font-sans text-lg">☛nombre de usuario</label>
    <input type="text" formControlName="name" class="rounded-sm border-white border-2 px-2 py-1 bg-black" required />

    <label class="font-sans text-lg">☛Contraseña</label>
    <input type="password" formControlName="password" class="rounded-sm border-white border-2 px-2 py-1 bg-black" required />

    <label class="font-sans text-lg">☛Carnet de identidad</label>
    <input type="text" formControlName="ci" class="rounded-sm border-white border-2 px-2 py-1 bg-black" required />

    <label class="font-sans text-lg">☛Numero de telefono</label>
    <input type="text" formControlName="telefono" class="rounded-sm border-white border-2 px-2 py-1 bg-black" required />

    <label class="font-sans text-lg">☛Tipo de usuario:</label>
    <select formControlName="role" class=" border-2 px-2 py-1 bg-black cursor-pointer text-green-500">
      <option value="">--Seleccione un rol--</option>
      <option value="vendedor">Vendedor</option>
      <option value="proveedor">Proveedor</option>
    </select>
    <button type="submit" class="font-sans font-bold border-2 border-white p-2 w-auto rounded-sm h-auto cursor-pointer">
      Crear cuenta
    </button>
    <!-- <div *ngIf="valido !== null" class="mt-2">
      <span *ngIf="valido" class="text-green-500">Registro exitoso</span>
      <span *ngIf="valido === false" class="text-red-500">Registro fallido</span>
    </div> -->
  </form>
</main>
  `,
  styles: ``
})
export class RegisterComponent {
  registerForm: FormGroup;
  // valido: boolean | null = null;

  constructor(
    private fb: FormBuilder,
    private router: Router,
    private authService: AuthService
  ) {
    this.registerForm = this.fb.group({
      name: ['', Validators.required],
      password: ['', Validators.required],
      ci: ['', Validators.required],
      telefono: ['', Validators.required],
      role: ['', Validators.required]
    });
  }

  home() {
    this.router.navigate(['']);
  }

 async onSubmit() {
    if (this.registerForm.invalid) return;
    try {
      await this.authService.register(this.registerForm.value);
      setTimeout(() => this.router.navigate(['']), 2000);
    } catch (error) {
      alert('Error al registrarse');
    }
  }
}
